apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api-deployment
spec:
  selector:
    matchLabels:
      app: api-pod
  replicas: 3
  template:
    metadata:
      labels:
        app: api-pod
    spec:
      containers:
        - image: gcr.io/serkan-tests/go-pg
          name: go-pg-api
          imagePullPolicy: "IfNotPresent"
          envFrom:
            - secretRef:
                name: go-pg-secret
          ports:
            - containerPort: 8080
              name: postgres
