apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-deployment # Name of the deployment
  labels:
    app: pg-deployment
spec:
  selector:
    matchLabels: # This deployment applies to the Pods matching the specified labels
      app: pg-pod
      tier: postgres
  replicas: 1
  template: # Template for the Pods in this deployment
    metadata:
      labels: # Labels to be applied to the Pods in this deployment
        app: pg-pod
        tier: postgres
    spec: # The spec for the containers that will be run inside the Pods in this deployment
      containers:
        - image: postgres:latest # The container image
          name: postgres
          imagePullPolicy: "IfNotPresent"
          envFrom: # Get the environmental variables from a secret file whose name is "postgres-secret"
            - secretRef:
                name: go-pg-secret
          ports:
            - containerPort: 5432 # The port that the container exposes
              name: postgres
