apiVersion: v1 # API version
kind: Service # Type of kubernetes resource
metadata:
  name: pg-service # Name of the resource
  labels: # Labels that will be applied to the resource
    app: pg-service
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector: # Selects any Pod with labels `app=pg-pod`
    app: pg-pod
    tier: postgres
